---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php support package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: update repository index for CentOS distro
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd and php support package in "CentOS"
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
